-- Topic pool v1 — 125 topics across 5 categories.
-- Generated from supabase/content/topics-v1.md. Edit that file and regenerate
-- rather than hand-patching rows here:
--
--   npm run db:seed
--
-- Category values are machine keys; the section headings in the source file are
-- the display names the client shows.
--
-- `on conflict (slug) do nothing` makes this safe to re-run and stops it from
-- overwriting edits made later in the dashboard.
--
--   mind        25
--   physics     25
--   nature      25
--   history     25
--   technology  25

insert into public.topics (slug, category, title, description, status) values
  ('dunning-kruger-effect', 'mind', 'Dunning-Kruger effect', 'A little knowledge produces a lot of confidence.', 'published'),
  ('the-monty-hall-problem', 'mind', 'The Monty Hall problem', 'Switching doubles your odds. Almost nobody believes it.', 'published'),
  ('the-birthday-paradox', 'mind', 'The birthday paradox', 'With 23 people, a shared birthday is more likely than not.', 'published'),
  ('the-bystander-effect', 'mind', 'The bystander effect', 'The more witnesses there are, the less likely anyone helps.', 'published'),
  ('sunk-cost-fallacy', 'mind', 'Sunk cost fallacy', 'Throwing good money after bad because you already paid.', 'published'),
  ('confirmation-bias', 'mind', 'Confirmation bias', 'We go looking for evidence of what we already believe.', 'published'),
  ('the-halo-effect', 'mind', 'The halo effect', 'Attractive people are assumed to be more competent as well.', 'published'),
  ('placebo-and-nocebo', 'mind', 'Placebo and nocebo', 'Expecting side effects is enough to produce them.', 'published'),
  ('the-cocktail-party-effect', 'mind', 'The cocktail party effect', 'Your own name cuts through any amount of noise.', 'published'),
  ('the-spotlight-effect', 'mind', 'The spotlight effect', 'Nobody noticed the stain on your shirt. Truly nobody.', 'published'),
  ('survivorship-bias', 'mind', 'Survivorship bias', 'The planes that did not come back had the bullet holes that mattered.', 'published'),
  ('anchoring', 'mind', 'Anchoring', 'An arbitrary number beforehand shifts every estimate that follows.', 'published'),
  ('the-zeigarnik-effect', 'mind', 'The Zeigarnik effect', 'Unfinished tasks stay in your head better than finished ones.', 'published'),
  ('the-hedonic-treadmill', 'mind', 'The hedonic treadmill', 'After every gain in happiness you return to where you started.', 'published'),
  ('the-prisoners-dilemma', 'mind', 'The prisoner''s dilemma', 'Two rational choices add up to the worst possible outcome.', 'published'),
  ('simpsons-paradox', 'mind', 'Simpson''s paradox', 'A trend reverses when you merge the groups.', 'published'),
  ('benfords-law', 'mind', 'Benford''s law', 'In real-world numbers, 1 leads far more often than 9. Used to catch fraud.', 'published'),
  ('regression-to-the-mean', 'mind', 'Regression to the mean', 'Why praise "does not work" and criticism appears to.', 'published'),
  ('the-pygmalion-effect', 'mind', 'The Pygmalion effect', 'Other people''s expectations change actual performance.', 'published'),
  ('the-peak-end-rule', 'mind', 'The peak-end rule', 'We judge experiences by their peak and their ending, not their length.', 'published'),
  ('choice-blindness', 'mind', 'Choice blindness', 'People confidently justify decisions they never made.', 'published'),
  ('dunbars-number', 'mind', 'Dunbar''s number', 'Around 150 stable relationships is the cognitive ceiling.', 'published'),
  ('semantic-satiation', 'mind', 'Semantic satiation', 'A word repeated often enough stops meaning anything.', 'published'),
  ('base-rate-neglect', 'mind', 'Base rate neglect', 'Why a positive test for a rare disease is usually wrong.', 'published'),
  ('the-decoy-effect', 'mind', 'The decoy effect', 'A third, worse option changes how you choose between the first two.', 'published'),
  ('the-fermi-paradox', 'physics', 'The Fermi paradox', 'The universe is vast and old. So where is everyone?', 'published'),
  ('time-dilation', 'physics', 'Time dilation', 'Moving clocks run slow. Measured, not theorised.', 'published'),
  ('why-astronauts-float', 'physics', 'Why astronauts float', 'Not because gravity is missing, but because they are permanently falling.', 'published'),
  ('tidal-locking', 'physics', 'Tidal locking', 'Why the Moon always shows us the same face.', 'published'),
  ('olbers-paradox', 'physics', 'Olbers'' paradox', 'If there are infinitely many stars, why is the night sky dark?', 'published'),
  ('quantum-entanglement', 'physics', 'Quantum entanglement', 'Two particles correlate across any distance without sending information.', 'published'),
  ('lagrange-points', 'physics', 'Lagrange points', 'Places in space where a satellite stays put. The James Webb telescope hangs at one.', 'published'),
  ('redshift', 'physics', 'Redshift', 'How we know the universe is expanding.', 'published'),
  ('the-cosmic-microwave-background', 'physics', 'The cosmic microwave background', 'The echo of the Big Bang, visible in the static of old televisions.', 'published'),
  ('the-light-year', 'physics', 'The light year', 'A distance, not a duration. Astronomy''s most common misunderstanding.', 'published'),
  ('dark-matter', 'physics', 'Dark matter', '85 per cent of the matter in the universe, and nobody knows what it is.', 'published'),
  ('heisenbergs-uncertainty-principle', 'physics', 'Heisenberg''s uncertainty principle', 'Not a limit of measurement, but a property of nature.', 'published'),
  ('entropy', 'physics', 'Entropy', 'Why time only runs in one direction.', 'published'),
  ('is-space-cold', 'physics', 'Is space cold?', 'A vacuum barely has a temperature. Freezing is not your main problem out there.', 'published'),
  ('the-doppler-effect', 'physics', 'The Doppler effect', 'Why an ambulance changes pitch as it passes you.', 'published'),
  ('kessler-syndrome', 'physics', 'Kessler syndrome', 'A chain reaction of orbital debris could make orbit unusable.', 'published'),
  ('why-rockets-do-not-fly-straight-up', 'physics', 'Why rockets do not fly straight up', 'You reach orbit through sideways speed, not altitude.', 'published'),
  ('the-roche-limit', 'physics', 'The Roche limit', 'Why moons break apart and turn into rings.', 'published'),
  ('antimatter', 'physics', 'Antimatter', 'It exists, we manufacture it, and nobody knows why there is so little of it.', 'published'),
  ('the-twin-paradox', 'physics', 'The twin paradox', 'The travelling twin comes back younger.', 'published'),
  ('where-heavy-elements-come-from', 'physics', 'Where heavy elements come from', 'The iron in your blood was made in a supernova.', 'published'),
  ('schroedingers-cat', 'physics', 'Schrödinger''s cat', 'Originally meant as criticism, today usually misquoted.', 'published'),
  ('the-planck-length', 'physics', 'The Planck length', 'The smallest distance it still makes sense to describe.', 'published'),
  ('solar-sails-and-light-pressure', 'physics', 'Solar sails and light pressure', 'Light has no rest mass but still exerts pressure.', 'published'),
  ('neutrinos', 'physics', 'Neutrinos', 'Billions pass through you every second without touching anything.', 'published'),
  ('endosymbiotic-theory', 'nature', 'Endosymbiotic theory', 'Your mitochondria were once free-living bacteria.', 'published'),
  ('trees-are-made-of-air', 'nature', 'Trees are made of air', 'A tree''s mass comes from CO2 in the air, not from the soil.', 'published'),
  ('the-amazon-is-not-the-lungs-of-the-earth', 'nature', 'The Amazon is not the lungs of the Earth', 'It consumes almost as much oxygen as it produces.', 'published'),
  ('mycorrhizal-networks', 'nature', 'Mycorrhizal networks', 'Fungi connect trees underground into a trading system.', 'published'),
  ('why-chilli-tastes-hot', 'nature', 'Why chilli tastes hot', 'Capsaicin fools heat receptors. Spiciness is not a taste.', 'published'),
  ('convergent-evolution', 'nature', 'Convergent evolution', 'Why dolphins and sharks look alike despite not being related.', 'published'),
  ('why-water-is-densest-at-4-degrees', 'nature', 'Why water is densest at 4 degrees', 'It is why lakes freeze from the top and the life in them survives.', 'published'),
  ('the-mpemba-effect', 'nature', 'The Mpemba effect', 'Under the right conditions, hot water freezes faster than cold.', 'published'),
  ('tardigrades', 'nature', 'Tardigrades', 'They survive vacuum, radiation and decades without water.', 'published'),
  ('petrichor', 'nature', 'Petrichor', 'The smell of rain comes from bacteria in the soil.', 'published'),
  ('clouds-weigh-tonnes', 'nature', 'Clouds weigh tonnes', 'An average cumulus weighs as much as 100 elephants and floats anyway.', 'published'),
  ('the-square-cube-law', 'nature', 'The square-cube law', 'Why elephants cannot jump and giant spiders are impossible.', 'published'),
  ('epigenetics', 'nature', 'Epigenetics', 'The environment can change gene activity across generations.', 'published'),
  ('why-antibiotics-do-not-work-on-viruses', 'nature', 'Why antibiotics do not work on viruses', 'Probably the most consequential everyday error in medicine.', 'published'),
  ('the-portuguese-man-o-war', 'nature', 'The Portuguese man o'' war', 'Not one animal but a colony of specialised organisms.', 'published'),
  ('why-stars-twinkle-and-planets-do-not', 'nature', 'Why stars twinkle and planets do not', 'A point source against a disc.', 'published'),
  ('bioluminescence', 'nature', 'Bioluminescence', 'Why deep-sea creatures glow and how they do it chemically.', 'published'),
  ('birds-flying-in-v-formation', 'nature', 'Birds flying in V formation', 'Aerodynamics, not sociability.', 'published'),
  ('the-eel', 'nature', 'The eel', 'Nobody has ever observed one reproducing in the wild.', 'published'),
  ('extremophiles-at-black-smokers', 'nature', 'Extremophiles at black smokers', 'Life without sunlight, running entirely on chemistry.', 'published'),
  ('the-foehn-wind', 'nature', 'The foehn wind', 'Why a wind brings rain on one side of a mountain and warmth on the other.', 'published'),
  ('plate-tectonics', 'nature', 'Plate tectonics', 'The Himalayas are still growing, centimetres every year.', 'published'),
  ('karst-and-sinkholes', 'nature', 'Karst and sinkholes', 'How water dissolves rock until the ground suddenly gives way.', 'published'),
  ('there-is-no-such-thing-as-cold-blooded', 'nature', 'There is no such thing as cold-blooded', 'Ectotherms are often warmer than you are.', 'published'),
  ('why-leaves-change-colour', 'nature', 'Why leaves change colour', 'The colours were there all along, just hidden by chlorophyll.', 'published'),
  ('vikings-did-not-wear-horned-helmets', 'history', 'Vikings did not wear horned helmets', 'The invention comes from an opera in 1876.', 'published'),
  ('the-potato-changed-europe', 'history', 'The potato changed Europe', 'It ended famines and made population growth possible.', 'published'),
  ('the-emu-war', 'history', 'The Emu War', 'In 1932 Australia sent the military against flightless birds and lost.', 'published'),
  ('the-library-of-alexandria', 'history', 'The Library of Alexandria', 'No single great fire, but centuries of decline.', 'published'),
  ('tulip-mania', 'history', 'Tulip mania', 'The first documented speculative bubble, Holland 1637.', 'published'),
  ('the-year-without-a-summer', 'history', 'The year without a summer', 'A volcanic eruption in 1815 caused crop failures worldwide and snow in June.', 'published'),
  ('the-silk-road-was-not-a-road', 'history', 'The Silk Road was not a road', 'It was a loose network, and the name was only coined in 1877.', 'published'),
  ('the-vasa', 'history', 'The Vasa', 'The prestige warship sank in 1628 after 1,300 metres.', 'published'),
  ('the-little-ice-age', 'history', 'The Little Ice Age', 'Centuries of colder climate, with consequences reaching into wars and witch trials.', 'published'),
  ('the-dark-ages', 'history', 'The "Dark Ages"', 'A polemical term from the Renaissance, historically hard to defend.', 'published'),
  ('napoleon-was-not-short', 'history', 'Napoleon was not short', 'Average height. The myth comes from British propaganda and units of measurement.', 'published'),
  ('the-spanish-flu-did-not-come-from-spain', 'history', 'The Spanish flu did not come from Spain', 'Spain simply did not censor the news.', 'published'),
  ('the-bronze-age-collapse', 'history', 'The Bronze Age collapse', 'Several advanced civilisations fell almost simultaneously around 1200 BC.', 'published'),
  ('stanislav-petrov', 'history', 'Stanislav Petrov', 'In 1983 an officer ignored a nuclear alert and probably prevented a world war.', 'published'),
  ('the-hanseatic-league', 'history', 'The Hanseatic League', 'A league of cities without a state that controlled northern European trade for centuries.', 'published'),
  ('the-fall-of-the-aztecs', 'history', 'The fall of the Aztecs', 'Disease killed far more people than weapons did.', 'published'),
  ('easter-island', 'history', 'Easter Island', 'The popular collapse narrative is now heavily disputed.', 'published'),
  ('the-longitude-problem', 'history', 'The longitude problem', 'A clockmaker solved the greatest navigation problem in seafaring.', 'published'),
  ('the-battle-of-cannae', 'history', 'The Battle of Cannae', 'How an outnumbered army destroyed a larger one by encirclement.', 'published'),
  ('the-berlin-conference', 'history', 'The Berlin Conference', 'Why Africa''s borders are so straight.', 'published'),
  ('witch-hunts-were-early-modern', 'history', 'Witch hunts were early modern', 'Their peak came after the Middle Ages, not during them.', 'published'),
  ('the-terracotta-army', 'history', 'The Terracotta Army', '8,000 figures, each with its own face, found by a man digging a well.', 'published'),
  ('the-black-death', 'history', 'The Black Death', 'Whether rats were really the main carrier is disputed.', 'published'),
  ('the-zimmermann-telegram', 'history', 'The Zimmermann telegram', 'A decrypted message pulled the United States into the First World War.', 'published'),
  ('the-mercator-projection', 'history', 'The Mercator projection', 'Why Greenland looks as big as Africa on maps despite being 14 times smaller.', 'published'),
  ('why-the-keyboard-is-laid-out-that-way', 'technology', 'Why the keyboard is laid out that way', 'The usual story about jamming typebars is disputed.', 'published'),
  ('the-streisand-effect', 'technology', 'The Streisand effect', 'Trying to delete something is what spreads it.', 'published'),
  ('the-y2k-bug', 'technology', 'The Y2K bug', 'That nothing happened was the result of years of work, not proof of panic-mongering.', 'published'),
  ('moores-law', 'technology', 'Moore''s law', 'Not a law of nature but an observation that became a target.', 'published'),
  ('gps-needs-relativity', 'technology', 'GPS needs relativity', 'Without correction your position would drift kilometres every day.', 'published'),
  ('incognito-mode-does-not-make-you-anonymous', 'technology', 'Incognito mode does not make you anonymous', 'It hides nothing from your provider, your employer or the site.', 'published'),
  ('the-turing-test', 'technology', 'The Turing test', 'What it measures is deception, not intelligence.', 'published'),
  ('why-progress-bars-lie', 'technology', 'Why progress bars lie', 'Progress indicators are mostly guessed, not measured.', 'published'),
  ('end-to-end-encryption', 'technology', 'End-to-end encryption', 'What it protects, and what stays visible anyway: the metadata.', 'published'),
  ('why-batteries-age', 'technology', 'Why batteries age', 'Chemical wear, and why charging to full accelerates it.', 'published'),
  ('training-versus-inference-in-ai', 'technology', 'Training versus inference in AI', 'Two completely different processes, constantly confused.', 'published'),
  ('why-language-models-hallucinate', 'technology', 'Why language models hallucinate', 'They predict probabilities. They do not look anything up.', 'published'),
  ('the-internet-is-not-a-cloud', 'technology', 'The internet is not a cloud', 'It is cables on the ocean floor, and sharks really do bite them.', 'published'),
  ('bluetooth-is-named-after-a-viking-king', 'technology', 'Bluetooth is named after a Viking king', 'The logo is his initials written in runes.', 'published'),
  ('the-first-computer-bug', 'technology', 'The first computer bug', 'Grace Hopper and the moth in the relay. The story is almost true.', 'published'),
  ('why-video-is-compressed', 'technology', 'Why video is compressed', 'Keyframes, motion vectors, and why fast scenes turn to mush.', 'published'),
  ('public-key-cryptography', 'technology', 'Public-key cryptography', 'How two strangers agree on a secret while everyone is listening.', 'published'),
  ('why-passwords-are-hashed', 'technology', 'Why passwords are hashed', 'And why a service that emails you your password has a problem.', 'published'),
  ('capacitive-touchscreens', 'technology', 'Capacitive touchscreens', 'Why gloves do not work but your finger does.', 'published'),
  ('placebo-buttons', 'technology', 'Placebo buttons', 'Many pedestrian crossing and door-close buttons are not connected to anything.', 'published'),
  ('why-aeroplane-mode-exists', 'technology', 'Why aeroplane mode exists', 'The actual reason is not that the plane would crash.', 'published'),
  ('random-versus-pseudorandom', 'technology', 'Random versus pseudorandom', 'Computers cannot roll dice. How they do it anyway.', 'published'),
  ('why-ssds-die-suddenly', 'technology', 'Why SSDs die suddenly', 'A different failure mode from hard drives, and without warning.', 'published'),
  ('rubber-duck-debugging', 'technology', 'Rubber duck debugging', 'Explaining a problem out loud solves it. The reason is psychologically interesting.', 'published'),
  ('the-history-of-the-at-sign', 'technology', 'The history of the @ sign', 'An accounting symbol made world-famous by a single decision in 1971.', 'published')
on conflict (slug) do nothing;
