-- Topic pool v1 — 125 topics across 5 categories.
-- Generated from supabase/content/topics-v1.md. Edit that file and regenerate
-- rather than hand-patching rows here:
--
--   npm run db:seed
--
-- Titles and descriptions are German because the pool is German. Category
-- values are English machine keys — the client maps them to display names.
--
-- `on conflict (slug) do nothing` makes this safe to re-run and stops it from
-- overwriting edits made later in the dashboard.
--
--   mind        25
--   physics     25
--   nature      25
--   history     25
--   technology  25

insert into public.topics (slug, category, title, description, status) values
  ('dunning-kruger-effekt', 'mind', 'Dunning-Kruger-Effekt', 'Wenig Wissen erzeugt hohe Selbstsicherheit.', 'published'),
  ('monty-hall-problem', 'mind', 'Monty-Hall-Problem', 'Wechseln verdoppelt die Gewinnchance. Fast niemand glaubt das.', 'published'),
  ('geburtstagsparadoxon', 'mind', 'Geburtstagsparadoxon', 'Ab 23 Personen ist ein gemeinsamer Geburtstag wahrscheinlicher als nicht.', 'published'),
  ('bystander-effekt', 'mind', 'Bystander-Effekt', 'Je mehr Zuschauer, desto unwahrscheinlicher die Hilfe.', 'published'),
  ('sunk-cost-fallacy', 'mind', 'Sunk Cost Fallacy', 'Man wirft gutem Geld schlechtes hinterher, weil man schon investiert hat.', 'published'),
  ('bestaetigungsfehler', 'mind', 'Bestätigungsfehler', 'Wir suchen Belege für das, was wir eh glauben.', 'published'),
  ('halo-effekt', 'mind', 'Halo-Effekt', 'Attraktive Menschen werden auch für kompetenter gehalten.', 'published'),
  ('placebo-und-nocebo-effekt', 'mind', 'Placebo- und Nocebo-Effekt', 'Auch die Erwartung von Nebenwirkungen erzeugt sie.', 'published'),
  ('cocktailparty-effekt', 'mind', 'Cocktailparty-Effekt', 'Der eigene Name dringt durch jeden Lärm.', 'published'),
  ('spotlight-effekt', 'mind', 'Spotlight-Effekt', 'Niemand bemerkt deinen Fleck auf dem Hemd. Wirklich niemand.', 'published'),
  ('survivorship-bias', 'mind', 'Survivorship Bias', 'Die Flugzeuge, die nicht zurückkamen, hatten die wichtigen Einschusslöcher.', 'published'),
  ('ankereffekt', 'mind', 'Ankereffekt', 'Eine willkürliche Zahl vorher verschiebt jede spätere Schätzung.', 'published'),
  ('zeigarnik-effekt', 'mind', 'Zeigarnik-Effekt', 'Unfertige Aufgaben bleiben besser im Kopf als erledigte.', 'published'),
  ('hedonistische-tretmuehle', 'mind', 'Hedonistische Tretmühle', 'Nach jedem Glücksgewinn kehrt man aufs Ausgangsniveau zurück.', 'published'),
  ('gefangenendilemma', 'mind', 'Gefangenendilemma', 'Zwei rationale Entscheidungen ergeben zusammen das schlechteste Ergebnis.', 'published'),
  ('simpson-paradoxon', 'mind', 'Simpson-Paradoxon', 'Ein Trend kehrt sich um, wenn man Gruppen zusammenlegt.', 'published'),
  ('benfords-gesetz', 'mind', 'Benfords Gesetz', 'In echten Zahlenreihen beginnt die 1 viel öfter als die 9. Wird zur Betrugserkennung genutzt.', 'published'),
  ('regression-zur-mitte', 'mind', 'Regression zur Mitte', 'Warum Lob "nicht wirkt" und Tadel scheinbar schon.', 'published'),
  ('pygmalion-effekt', 'mind', 'Pygmalion-Effekt', 'Erwartungen anderer verändern die tatsächliche Leistung.', 'published'),
  ('peak-end-regel', 'mind', 'Peak-End-Regel', 'Wir bewerten Erlebnisse nach dem Höhepunkt und dem Ende, nicht nach der Dauer.', 'published'),
  ('choice-blindness', 'mind', 'Choice Blindness', 'Menschen begründen Entscheidungen, die sie gar nicht getroffen haben.', 'published'),
  ('dunbar-zahl', 'mind', 'Dunbar-Zahl', 'Etwa 150 stabile Beziehungen sind die kognitive Obergrenze.', 'published'),
  ('semantische-saettigung', 'mind', 'Semantische Sättigung', 'Ein oft wiederholtes Wort verliert seine Bedeutung.', 'published'),
  ('basisratenfehler', 'mind', 'Basisratenfehler', 'Warum ein positiver Test bei einer seltenen Krankheit meist falsch ist.', 'published'),
  ('koeder-effekt-decoy', 'mind', 'Köder-Effekt (Decoy)', 'Eine dritte, schlechtere Option verändert die Wahl zwischen den ersten beiden.', 'published'),
  ('fermi-paradoxon', 'physics', 'Fermi-Paradoxon', 'Das Universum ist riesig und alt. Wo sind alle?', 'published'),
  ('zeitdilatation', 'physics', 'Zeitdilatation', 'Bewegte Uhren gehen langsamer. Messbar, nicht theoretisch.', 'published'),
  ('warum-astronauten-schweben', 'physics', 'Warum Astronauten schweben', 'Nicht wegen fehlender Schwerkraft, sondern weil sie permanent fallen.', 'published'),
  ('gebundene-rotation', 'physics', 'Gebundene Rotation', 'Warum der Mond uns immer dieselbe Seite zeigt.', 'published'),
  ('olbers-paradoxon', 'physics', 'Olbers-Paradoxon', 'Warum ist der Nachthimmel dunkel, wenn es unendlich viele Sterne gibt?', 'published'),
  ('quantenverschraenkung', 'physics', 'Quantenverschränkung', 'Zwei Teilchen korrelieren über beliebige Distanz, ohne Information zu senden.', 'published'),
  ('lagrange-punkte', 'physics', 'Lagrange-Punkte', 'Orte im All, an denen ein Satellit "stehen bleibt". Dort hängt das James-Webb-Teleskop.', 'published'),
  ('rotverschiebung', 'physics', 'Rotverschiebung', 'Woher wir wissen, dass sich das Universum ausdehnt.', 'published'),
  ('kosmische-hintergrundstrahlung', 'physics', 'Kosmische Hintergrundstrahlung', 'Das Echo des Urknalls, sichtbar im Rauschen alter Fernseher.', 'published'),
  ('lichtjahr', 'physics', 'Lichtjahr', 'Eine Entfernung, keine Zeitangabe. Häufigstes Missverständnis der Astronomie.', 'published'),
  ('dunkle-materie', 'physics', 'Dunkle Materie', '85 % der Materie im Universum, und niemand weiß, was es ist.', 'published'),
  ('heisenbergsche-unschaerferelation', 'physics', 'Heisenbergsche Unschärferelation', 'Keine Messungenauigkeit, sondern eine Eigenschaft der Natur.', 'published'),
  ('entropie', 'physics', 'Entropie', 'Warum die Zeit nur in eine Richtung läuft.', 'published'),
  ('ist-der-weltraum-kalt', 'physics', 'Ist der Weltraum kalt?', 'Ein Vakuum hat kaum Temperatur. Erfrieren ist dort nicht das Hauptproblem.', 'published'),
  ('doppler-effekt', 'physics', 'Doppler-Effekt', 'Warum der Krankenwagen beim Vorbeifahren die Tonhöhe wechselt.', 'published'),
  ('kessler-syndrom', 'physics', 'Kessler-Syndrom', 'Eine Kettenreaktion aus Weltraumschrott könnte den Orbit unbrauchbar machen.', 'published'),
  ('warum-raketen-nicht-geradeaus-fliegen', 'physics', 'Warum Raketen nicht geradeaus fliegen', 'In den Orbit kommt man durch seitliche Geschwindigkeit, nicht durch Höhe.', 'published'),
  ('roche-grenze', 'physics', 'Roche-Grenze', 'Warum Monde zerbrechen und daraus Ringe entstehen.', 'published'),
  ('antimaterie', 'physics', 'Antimaterie', 'Existiert, wird hergestellt, und niemand weiß, warum es davon so wenig gibt.', 'published'),
  ('zwillingsparadoxon', 'physics', 'Zwillingsparadoxon', 'Der reisende Zwilling kommt jünger zurück.', 'published'),
  ('woher-schwere-elemente-kommen', 'physics', 'Woher schwere Elemente kommen', 'Das Eisen in deinem Blut entstand in einer Supernova.', 'published'),
  ('schroedingers-katze', 'physics', 'Schrödingers Katze', 'Ursprünglich als Kritik gemeint, heute meist falsch zitiert.', 'published'),
  ('planck-laenge', 'physics', 'Planck-Länge', 'Die kleinste sinnvoll beschreibbare Distanz.', 'published'),
  ('sonnensegel-und-lichtdruck', 'physics', 'Sonnensegel und Lichtdruck', 'Licht hat keinen Ruhemasse, übt aber Druck aus.', 'published'),
  ('neutrinos', 'physics', 'Neutrinos', 'Milliarden durchqueren dich pro Sekunde, ohne etwas zu berühren.', 'published'),
  ('endosymbiontentheorie', 'nature', 'Endosymbiontentheorie', 'Deine Mitochondrien waren einmal eigenständige Bakterien.', 'published'),
  ('baeume-bestehen-aus-luft', 'nature', 'Bäume bestehen aus Luft', 'Die Masse eines Baums kommt aus CO₂, nicht aus dem Boden.', 'published'),
  ('der-amazonas-ist-nicht-die-lunge-der-erde', 'nature', 'Der Amazonas ist nicht die Lunge der Erde', 'Er verbraucht fast so viel Sauerstoff, wie er produziert.', 'published'),
  ('mykorrhiza-netzwerke', 'nature', 'Mykorrhiza-Netzwerke', 'Pilze verbinden Bäume unterirdisch zu einem Austauschsystem.', 'published'),
  ('warum-chili-scharf-schmeckt', 'nature', 'Warum Chili scharf schmeckt', 'Capsaicin täuscht Wärmerezeptoren. Schärfe ist kein Geschmack.', 'published'),
  ('konvergente-evolution', 'nature', 'Konvergente Evolution', 'Warum Delfin und Hai gleich aussehen, obwohl sie nicht verwandt sind.', 'published'),
  ('warum-wasser-bei-4-c-am-dichtesten-ist', 'nature', 'Warum Wasser bei 4 °C am dichtesten ist', 'Deshalb frieren Seen von oben zu und das Leben darin überlebt.', 'published'),
  ('mpemba-effekt', 'nature', 'Mpemba-Effekt', 'Unter bestimmten Bedingungen gefriert heißes Wasser schneller als kaltes.', 'published'),
  ('baertierchen', 'nature', 'Bärtierchen', 'Überleben Vakuum, Strahlung und Jahrzehnte ohne Wasser.', 'published'),
  ('petrichor', 'nature', 'Petrichor', 'Der Geruch von Regen kommt von Bakterien im Boden.', 'published'),
  ('wolken-wiegen-tonnen', 'nature', 'Wolken wiegen Tonnen', 'Eine mittlere Cumuluswolke wiegt so viel wie 100 Elefanten und schwebt trotzdem.', 'published'),
  ('quadrat-kubik-gesetz', 'nature', 'Quadrat-Kubik-Gesetz', 'Warum Elefanten nicht springen und Riesenspinnen unmöglich sind.', 'published'),
  ('epigenetik', 'nature', 'Epigenetik', 'Umwelteinflüsse können die Genaktivität über Generationen verändern.', 'published'),
  ('warum-antibiotika-bei-viren-nicht-wirken', 'nature', 'Warum Antibiotika bei Viren nicht wirken', 'Der wohl folgenreichste Alltagsirrtum der Medizin.', 'published'),
  ('die-portugiesische-galeere', 'nature', 'Die Portugiesische Galeere', 'Kein einzelnes Tier, sondern eine Kolonie aus spezialisierten Einzelorganismen.', 'published'),
  ('warum-sterne-funkeln-planeten-aber-nicht', 'nature', 'Warum Sterne funkeln, Planeten aber nicht', 'Punktlichtquelle gegen Scheibe.', 'published'),
  ('bioluminszenz', 'nature', 'Bioluminszenz', 'Warum Tiefseetiere leuchten und wie sie es chemisch machen.', 'published'),
  ('zugvoegel-in-v-formation', 'nature', 'Zugvögel in V-Formation', 'Aerodynamik, nicht Geselligkeit.', 'published'),
  ('der-aal', 'nature', 'Der Aal', 'Man hat bis heute nie eine Fortpflanzung in freier Wildbahn beobachtet.', 'published'),
  ('extremophile-an-schwarzen-rauchern', 'nature', 'Extremophile an schwarzen Rauchern', 'Leben ohne Sonnenlicht, komplett auf Chemie basierend.', 'published'),
  ('foehn', 'nature', 'Föhn', 'Warum ein Wind auf der einen Seite des Bergs Regen bringt und auf der anderen Wärme.', 'published'),
  ('plattentektonik', 'nature', 'Plattentektonik', 'Der Himalaya wächst noch immer, jedes Jahr um Zentimeter.', 'published'),
  ('karst-und-dolinen', 'nature', 'Karst und Dolinen', 'Wie Wasser Gestein auflöst und der Boden plötzlich einbricht.', 'published'),
  ('kaltblueter-gibt-es-nicht', 'nature', 'Kaltblüter gibt es nicht', 'Wechselwarme Tiere sind oft wärmer als du.', 'published'),
  ('warum-blaetter-sich-verfaerben', 'nature', 'Warum Blätter sich verfärben', 'Die Farben waren die ganze Zeit da, nur vom Chlorophyll überdeckt.', 'published'),
  ('wikinger-trugen-keine-hoernerhelme', 'history', 'Wikinger trugen keine Hörnerhelme', 'Die Erfindung stammt aus einer Oper von 1876.', 'published'),
  ('die-kartoffel-veraenderte-europa', 'history', 'Die Kartoffel veränderte Europa', 'Sie beendete Hungersnöte und ermöglichte Bevölkerungswachstum.', 'published'),
  ('der-emu-krieg', 'history', 'Der Emu-Krieg', 'Australien schickte 1932 das Militär gegen Laufvögel und verlor.', 'published'),
  ('die-bibliothek-von-alexandria', 'history', 'Die Bibliothek von Alexandria', 'Kein großer Brand, sondern jahrhundertelanger Verfall.', 'published'),
  ('tulpenmanie', 'history', 'Tulpenmanie', 'Die erste dokumentierte Spekulationsblase, 1637 in Holland.', 'published'),
  ('das-jahr-ohne-sommer', 'history', 'Das Jahr ohne Sommer', 'Ein Vulkanausbruch 1815 verursachte weltweit Missernten und Schnee im Juni.', 'published'),
  ('die-seidenstrasse-war-keine-strasse', 'history', 'Die Seidenstraße war keine Straße', 'Sondern ein loses Netz, und der Name wurde erst 1877 erfunden.', 'published'),
  ('die-vasa', 'history', 'Die Vasa', 'Das Prestigeschiff sank 1628 nach 1300 Metern Fahrt.', 'published'),
  ('die-kleine-eiszeit', 'history', 'Die Kleine Eiszeit', 'Jahrhunderte kälteres Klima, mit Folgen bis in Kriege und Hexenprozesse.', 'published'),
  ('das-finstere-mittelalter', 'history', 'Das "finstere Mittelalter"', 'Ein Kampfbegriff der Renaissance, historisch kaum haltbar.', 'published'),
  ('napoleon-war-nicht-klein', 'history', 'Napoleon war nicht klein', 'Durchschnittsgröße. Der Mythos kommt aus britischer Propaganda und Maßeinheiten.', 'published'),
  ('die-spanische-grippe-kam-nicht-aus-spanien', 'history', 'Die Spanische Grippe kam nicht aus Spanien', 'Spanien zensierte nur nicht.', 'published'),
  ('der-bronzezeitkollaps', 'history', 'Der Bronzezeitkollaps', 'Mehrere Hochkulturen brachen um 1200 v. Chr. fast gleichzeitig zusammen.', 'published'),
  ('stanislaw-petrow', 'history', 'Stanislaw Petrow', 'Ein Offizier ignorierte 1983 einen Atomalarm und verhinderte vermutlich den Weltkrieg.', 'published'),
  ('die-hanse', 'history', 'Die Hanse', 'Ein Städtebund ohne Staat, der Jahrhunderte Nordeuropas Handel kontrollierte.', 'published'),
  ('der-untergang-der-azteken', 'history', 'Der Untergang der Azteken', 'Krankheiten töteten weit mehr als Waffen.', 'published'),
  ('die-osterinsel', 'history', 'Die Osterinsel', 'Das populäre Kollapsnarrativ gilt heute als stark umstritten.', 'published'),
  ('die-laengengrad-frage', 'history', 'Die Längengrad-Frage', 'Ein Uhrmacher löste das größte Navigationsproblem der Seefahrt.', 'published'),
  ('die-schlacht-von-cannae', 'history', 'Die Schlacht von Cannae', 'Wie eine unterlegene Armee durch Umfassung eine größere vernichtete.', 'published'),
  ('die-berliner-konferenz', 'history', 'Die Berliner Konferenz', 'Warum Afrikas Grenzen so gerade sind.', 'published'),
  ('hexenverfolgungen-waren-fruehneuzeitlich', 'history', 'Hexenverfolgungen waren frühneuzeitlich', 'Ihr Höhepunkt lag nach dem Mittelalter, nicht darin.', 'published'),
  ('die-terrakotta-armee', 'history', 'Die Terrakotta-Armee', '8.000 Figuren, jede mit eigenem Gesicht, gefunden von einem Brunnenbauern.', 'published'),
  ('der-schwarze-tod', 'history', 'Der Schwarze Tod', 'Ob die Ratte wirklich der Hauptüberträger war, ist umstritten.', 'published'),
  ('das-zimmermann-telegramm', 'history', 'Das Zimmermann-Telegramm', 'Eine entschlüsselte Nachricht zog die USA in den Ersten Weltkrieg.', 'published'),
  ('die-mercator-projektion', 'history', 'Die Mercator-Projektion', 'Warum Grönland auf Karten so groß aussieht wie Afrika, obwohl es 14-mal kleiner ist.', 'published'),
  ('warum-die-tastatur-so-angeordnet-ist', 'technology', 'Warum die Tastatur so angeordnet ist', 'Die gängige Erklärung mit den verhakenden Typenhebeln ist umstritten.', 'published'),
  ('der-streisand-effekt', 'technology', 'Der Streisand-Effekt', 'Etwas löschen zu wollen, verbreitet es erst recht.', 'published'),
  ('der-y2k-bug', 'technology', 'Der Y2K-Bug', 'Dass nichts passierte, war das Ergebnis jahrelanger Arbeit, kein Beweis für Panikmache.', 'published'),
  ('moores-gesetz', 'technology', 'Moores Gesetz', 'Kein Naturgesetz, sondern eine Beobachtung, die zur Zielvorgabe wurde.', 'published'),
  ('gps-braucht-relativitaetstheorie', 'technology', 'GPS braucht Relativitätstheorie', 'Ohne Korrektur läge dein Standort täglich um Kilometer daneben.', 'published'),
  ('der-inkognito-modus-macht-nicht-anonym', 'technology', 'Der Inkognito-Modus macht nicht anonym', 'Er verbirgt nichts vor Anbieter, Arbeitgeber oder Website.', 'published'),
  ('der-turing-test', 'technology', 'Der Turing-Test', 'Was er misst, ist Täuschung, nicht Intelligenz.', 'published'),
  ('warum-ladebalken-luegen', 'technology', 'Warum Ladebalken lügen', 'Fortschrittsanzeigen sind meist geraten, nicht gemessen.', 'published'),
  ('ende-zu-ende-verschluesselung', 'technology', 'Ende-zu-Ende-Verschlüsselung', 'Was sie schützt und was trotzdem sichtbar bleibt (Metadaten).', 'published'),
  ('warum-akkus-altern', 'technology', 'Warum Akkus altern', 'Chemischer Verschleiß, und warum Vollladen ihn beschleunigt.', 'published'),
  ('training-vs-inferenz-bei-ki', 'technology', 'Training vs. Inferenz bei KI', 'Zwei völlig verschiedene Vorgänge, ständig verwechselt.', 'published'),
  ('warum-sprachmodelle-halluzinieren', 'technology', 'Warum Sprachmodelle halluzinieren', 'Sie sagen Wahrscheinlichkeiten voraus, sie schlagen nichts nach.', 'published'),
  ('das-internet-ist-keine-wolke', 'technology', 'Das Internet ist keine Wolke', 'Es sind Seekabel am Meeresboden, und Haie beißen tatsächlich hinein.', 'published'),
  ('bluetooth-ist-nach-einem-wikingerkoenig-benannt', 'technology', 'Bluetooth ist nach einem Wikingerkönig benannt', 'Das Logo besteht aus seinen Initialen in Runen.', 'published'),
  ('der-erste-computer-bug', 'technology', 'Der erste Computer-Bug', 'Grace Hopper und die Motte im Relais. Die Geschichte stimmt fast.', 'published'),
  ('warum-videos-komprimiert-werden', 'technology', 'Warum Videos komprimiert werden', 'Keyframes, Bewegungsvektoren, und warum schnelle Szenen matschig werden.', 'published'),
  ('public-key-kryptografie', 'technology', 'Public-Key-Kryptografie', 'Wie zwei Fremde ein Geheimnis vereinbaren, während alle zuhören.', 'published'),
  ('warum-passwoerter-gehasht-werden', 'technology', 'Warum Passwörter gehasht werden', 'Und warum ein Anbieter, der dir dein Passwort zusendet, ein Problem hat.', 'published'),
  ('kapazitive-touchscreens', 'technology', 'Kapazitive Touchscreens', 'Warum Handschuhe nicht funktionieren, dein Finger aber schon.', 'published'),
  ('placebo-buttons', 'technology', 'Placebo-Buttons', 'Viele Ampelknöpfe und Fahrstuhl-Schließknöpfe sind nicht angeschlossen.', 'published'),
  ('warum-es-den-flugmodus-gibt', 'technology', 'Warum es den Flugmodus gibt', 'Die tatsächliche Begründung ist nicht der Absturz.', 'published'),
  ('zufall-vs-pseudozufall', 'technology', 'Zufall vs. Pseudozufall', 'Computer können nicht würfeln. Wie sie es trotzdem tun.', 'published'),
  ('warum-ssds-ploetzlich-sterben', 'technology', 'Warum SSDs plötzlich sterben', 'Andere Ausfallart als Festplatten, ohne Vorwarnung.', 'published'),
  ('rubber-duck-debugging', 'technology', 'Rubber Duck Debugging', 'Ein Problem laut erklären löst es. Der Grund dahinter ist psychologisch interessant.', 'published'),
  ('die-geschichte-des-zeichens', 'technology', 'Die Geschichte des @-Zeichens', 'Ein Buchhaltungszeichen, das durch eine einzige Entscheidung 1971 weltberühmt wurde.', 'published')
on conflict (slug) do nothing;
