-- speech_sessions.client_id -> client_session_id
--
-- The column was documented as a "device UUID". Combined with the unique index
-- on (user_id, client_id) that allowed exactly ONE session per user and device:
-- a device UUID is constant across sessions, so the second recording on the
-- same phone would fail with a unique violation.
--
-- The index was never the problem — the column's meaning was. What it has to
-- hold is a per-session idempotency key, generated fresh by the client for each
-- recording, so that retrying a failed upload hits the existing row instead of
-- inserting a duplicate.
--
-- Renaming instead of dropping/re-adding keeps the unique index (Postgres
-- follows the column) and therefore the guarantee. The table is empty and no
-- client writes to it yet, so there is nothing to backfill.
alter table public.speech_sessions
  rename column client_id to client_session_id;

alter index speech_sessions_user_client_idx
  rename to speech_sessions_user_client_session_idx;

-- Pin the meaning in the database itself, where Studio and generated docs show
-- it. A misleading comment is what caused this in the first place.
comment on column public.speech_sessions.client_session_id is
  'Idempotency key generated by the client per recording session (NOT a device id). Unique per user, so retrying an upload updates the existing row instead of inserting a duplicate.';
